#extent properties

extent.reporter.spark.start=true
extent.reporter.spark.out=report/CucumberExtentReport.html

extent.reporter.spark.theme=standard
extent.reporter.spark.document.title=Cucumber Test Automation Report
extent.reporter.spark.report.name=Cucumber Test Automation Report

screenshot.dir=screenshots/
screenshot.rel.path=../screenshots/

basefolder.name=reports/extent-reports
basefolder.datetimepattern=yyyyMMdd_HHmmss

